---
- name: Cria a máquina virtual
  vmware_guest:
    hostname: 192.168.0.50
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    folder: FNCIT/vm
    datacenter: FNCIT
    cluster: FNCLAB
    name: "{{ vm_name }}" 
    template: fncsrvdocker
    state: poweredon
    wait_for_ip_address: yes

- name: Armazena facts da vm recém criada
  vmware_guest_facts:
    hostname: 192.168.0.50
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    datacenter: FNCIT
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: facts

- name: Debuga o IP
  debug: msg="Ip da maquina {{ facts.instance.ipv4 }}"

- name: Adiciona o host novamaquina 
  add_host:
    name: "{{ facts.instance.ipv4 }}"
    groups: novamaquina
    ansible_ssh_pass: Uru100bu
